import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

import {
  canonicalDigest,
  canonicalFile,
} from "../src/adaptive-evidence-contracts.mjs";
import { sha256 } from "../src/io.mjs";

async function builder() {
  return import("../scripts/build-adaptive-evidence-portfolio-v1.mjs").catch((error) =>
    assert.fail(`portfolio receipt builder is unavailable: ${error.message}`));
}

test("builds a deterministic two-task structural portfolio release", async () => {
  const { rebuildAdaptiveEvidencePortfolioV1 } = await builder();
  const first = await rebuildAdaptiveEvidencePortfolioV1();
  const second = await rebuildAdaptiveEvidencePortfolioV1();
  assert.equal(canonicalFile(second.receipt), canonicalFile(first.receipt));
  assert.equal(canonicalFile(second.plan), canonicalFile(first.plan));
  assert.equal(canonicalFile(second.report), canonicalFile(first.report));
  assert.deepEqual(
    second.members.map(({ completion }) => completion.completionDigest),
    first.members.map(({ completion }) => completion.completionDigest),
  );

  assert.equal(first.receipt.schemaVersion, 1);
  assert.equal(first.receipt.id, "adaptive-evidence-portfolio-v1");
  assert.equal(first.receipt.status, "verified-structural-protocol");
  assert.equal(first.receipt.protocolId, "eternities-godskills-cross-trial-portfolio-v1");
  assert.equal(first.receipt.authorityExpanded, false);
  assert.equal(first.receipt.profilePromotionAllowed, false);
  assert.equal(first.receipt.lifecycleActionAllowed, false);
  assert.equal(first.receipt.activationRequestAllowed, false);
  const { receiptDigest, ...receiptBody } = first.receipt;
  assert.equal(receiptDigest, canonicalDigest(receiptBody));

  assert.deepEqual(first.receipt.parents.adaptiveEvidenceV2, {
    path: "receipts/adaptive-evidence-v2.json",
    receiptDigest: "2ed01045d7e25e1c737ef375ae472757edff1459fa5c9dd49ec77572f33f6a8d",
    sha256: "7f84e36cd9d02d4c93f2348500d16c6fe93b8b357d1d97c271de418cdd29b56a",
    bytes: 14138,
  });
  assert.deepEqual(first.receipt.parents.adaptiveEvaluatorPackagesV1, {
    path: "receipts/adaptive-evaluator-packages-v1.json",
    receiptDigest: "a7649453504001333f103521d4dfe1e016de7041b70c6d910507c7d1734f1334",
    sha256: "ae7ded06bbed4aa0e2dea32dad9f841c1427f9abade57b86ad19c25b261bd519",
    bytes: 9578,
  });

  assert.equal(first.plan.taskSlots.length, 2);
  assert.equal(first.members.length, 2);
  assert.equal(new Set(first.members.map(({ ledger }) => ledger.ledgerDigest)).size, 2);
  assert.equal(first.report.completedTaskCount, 2);
  assert.deepEqual(first.report.candidatesPassingEvidenceGate, ["guardrail"]);
  const method = first.report.variantMetrics.find(({ variant }) => variant === "method");
  assert.equal(method.wins, 2);
  assert.equal(method.criticalRegressions, 1);
  assert.equal(method.passedEvidenceGate, false);
  assert.ok(method.failedGates.includes("worst-task-critical-regression"));

  const internalMatchedCounts = first.members.map(({ ledger }) =>
    ledger.rows.find(({ variant }) => variant === "guardrail").comparisons.matched);
  assert.deepEqual(internalMatchedCounts, [3, 3000]);
  const guardrail = first.report.variantMetrics.find(({ variant }) => variant === "guardrail");
  assert.equal(guardrail.completedTasks, 2);
  assert.equal(guardrail.wins, 2);
  assert.equal("matchedComparisons" in guardrail, false);
  assert.equal(first.report.caseComparisonAggregationAllowed, false);
});

test("release receipt binds every generated byte and source boundary", async () => {
  const { rebuildAdaptiveEvidencePortfolioV1 } = await builder();
  const result = await rebuildAdaptiveEvidencePortfolioV1();
  const outputByPath = new Map(result.receipt.outputs.map((entry) => [entry.path, entry]));
  assert.equal(outputByPath.size, Object.keys(result.writes).length - 1);
  for (const [path, text] of Object.entries(result.writes)) {
    if (path === "receipts/adaptive-evidence-portfolio-v1.json") continue;
    const record = outputByPath.get(path);
    assert.ok(record, `missing output manifest for ${path}`);
    assert.equal(record.sha256, sha256(text));
    assert.equal(record.bytes, Buffer.byteLength(text));
  }
  assert.deepEqual(result.receipt.computedGates, {
    exactPreregisteredTaskCount: 2,
    exactCompletedTaskCount: 2,
    independentLedgerCount: 2,
    taskOutcomesPerCandidate: 2,
    internalCaseCountsExcluded: true,
    worstTaskCriticalRegressionGateExercised: true,
    completeCohortRequired: true,
    profilePromotionAllowed: false,
    lifecycleActionAllowed: false,
    activationRequestAllowed: false,
    authorityExpansions: 0,
  });
  assert.ok(result.receipt.inputs.sources.some(({ path }) =>
    path === "src/adaptive-evidence-portfolio.mjs"));
  assert.ok(result.receipt.inputs.sources.some(({ path }) =>
    path === "tests/adaptive-evidence-portfolio.test.mjs"));
  assert.ok(result.receipt.proofLimits.includes("fixtures-are-not-model-quality-evidence"));
  assert.ok(result.receipt.proofLimits.includes("no-godagents-activation"));
});

test("direct builder and generated schemas preserve the parent-bound package manifest", async () => {
  const [{ rebuildAdaptiveEvidencePortfolioV1 }, packageText] = await Promise.all([
    builder(),
    readFile(new URL("../package.json", import.meta.url), "utf8"),
  ]);
  const packageJson = JSON.parse(packageText);
  assert.equal(packageJson.scripts["build:adaptive-evidence-portfolio"], undefined);
  const result = await rebuildAdaptiveEvidencePortfolioV1();
  assert.deepEqual(Object.keys(result.schemas).sort(), ["completion", "plan", "report"]);
  assert.equal(result.schemas.report.additionalProperties, false);
  assert.equal(result.schemas.report.properties.reportingOnly.const, true);
  assert.equal(result.schemas.report.properties.profilePromotionAllowed.const, false);
});
