import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { mkdtemp, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import test from 'node:test';
import { compileAndRouteEffectOnlyV2 } from '../src/effect-intent-v2.mjs';

const root = fileURLToPath(new URL('../', import.meta.url));
const cli = path.join(root,'scripts/verify-effect-only-v2.mjs');
const vector = JSON.parse(await readFile(path.join(root,'data/effect-only-golden-vector-v2.json')));
const checked = JSON.parse(await readFile(path.join(root,'data/effect-only-result-v2.json')));
const hash = value => createHash('sha256').update(JSON.stringify(value,(_k,v) =>
  v && typeof v === 'object' && !Array.isArray(v) ? Object.fromEntries(Object.keys(v).sort().map(k=>[k,v[k]])) : v)).digest('hex');

async function fixture(t) {
  const folder = await mkdtemp(path.join(tmpdir(),'effect-verifier-'));
  t.after(()=>rm(folder,{recursive:true,force:true}));
  const request = path.join(folder,'request.json');
  const source = path.join(folder,'source.json');
  const result = path.join(folder,'result.json');
  await writeFile(request,JSON.stringify(vector.request));
  await writeFile(source,JSON.stringify(vector.expectedSource));
  await writeFile(result,JSON.stringify(checked));
  return {folder,request,source,result,args:['--request',request,'--expected-source',source,'--result',result]};
}
async function snapshot(folder) {
  return Promise.all((await readdir(folder)).sort().map(async name => [name,(await readFile(path.join(folder,name))).toString('base64')]));
}
function run(f,args=f.args) {
  const env={};
  for(const key of ['SystemRoot','WINDIR']) if(process.env[key]) env[key]=process.env[key];
  return spawnSync(process.execPath,[cli,...args],{cwd:f.folder,env,encoding:'utf8',windowsHide:true,timeout:5000,maxBuffer:4096});
}

test('exact checked pair verifies with no output and no filesystem mutation',async t=>{
  const f=await fixture(t); const before=await snapshot(f.folder);
  const child=run(f);
  assert.equal(child.status,0,child.stderr); assert.equal(child.stdout,''); assert.equal(child.stderr,'');
  assert.deepEqual(await snapshot(f.folder),before);
});

for(const state of ['denied','unknown','conflicting']) test(`exact ${state} needs-decision verifies without implying permission`,async t=>{
  const f=await fixture(t); const request=structuredClone(vector.request);
  if(state==='denied') request.context.availableAuthority=['local-read'];
  else Object.assign(request.effectAssessment,{state,requestedEffects:[],unresolvedDecisions:['producer-needs-input']});
  const expectedSource={...vector.expectedSource,requestDigest:hash(request)};
  // Fixture generated by frozen parent consumer; wrapper must verify it, not
  // reinterpret needs-decision as failure or emit a new result.
  const result=compileAndRouteEffectOnlyV2({request,expectedSource});
  assert.equal(result.routeReceipt.status,'needs-decision');
  await writeFile(f.request,JSON.stringify(request)); await writeFile(f.source,JSON.stringify(expectedSource));
  await writeFile(f.result,JSON.stringify(result)); const before=await snapshot(f.folder);
  const child=run(f); assert.equal(child.status,0,child.stderr); assert.equal(child.stdout,'');
  assert.deepEqual(await snapshot(f.folder),before);
});

for(const [label,change] of [
  ['missing result', a=>a.slice(0,4)], ['missing source',a=>[...a.slice(0,2),...a.slice(4)]],
  ['missing request',a=>a.slice(2)], ['duplicate flag',a=>[...a,'--result',a[5]]],
  ['output option',a=>[...a,'--output','new.json']], ['mode option',a=>[...a,'--mode','route']],
  ['model option',a=>[...a,'--model','none']], ['dangling path',a=>a.slice(0,5)],
]) test(`rejects ${label} without changes`,async t=>{
  const f=await fixture(t); const before=await snapshot(f.folder); const child=run(f,change(f.args));
  assert.equal(child.status,1); assert.equal(child.stdout,''); assert.match(child.stderr,/effect-only-verifier-v2:/);
  assert.deepEqual(await snapshot(f.folder),before);
});

for(const [label,field,mutate] of [
  ['changed text','request',v=>{v.text+=' changed';}],
  ['changed subject','source',v=>{v.subjectDigest='0'.repeat(64);}],
  ['changed producer','source',v=>{v.producerDescriptorDigest='0'.repeat(64);}],
  ['changed R','source',v=>{v.requestDigest='0'.repeat(64);}],
  ['changed result status','result',v=>{v.routeReceipt.status='selected';}],
  ['changed assessment','result',v=>{v.compilerReceipt.assessmentBinding.state='unknown';}],
  ['extra result field','result',v=>{v.allow=true;}],
  ['missing result field','result',v=>{delete v.compilerReceipt.textDigest;}],
]) test(`rejects ${label} and never repairs evidence`,async t=>{
  const f=await fixture(t); const value=JSON.parse(await readFile(f[field])); mutate(value);
  await writeFile(f[field],JSON.stringify(value)); const before=await snapshot(f.folder);
  const child=run(f); assert.equal(child.status,1); assert.equal(child.stdout,'');
  assert.match(child.stderr,/verification mismatch/); assert.deepEqual(await snapshot(f.folder),before);
});

for(const [field,limit] of [['request',1024*1024],['source',1024*1024],['result',2*1024*1024]]) {
  test(`bounds ${field} bytes before semantic validation`,async t=>{
    const f=await fixture(t); await writeFile(f[field],JSON.stringify({privateContent:'x'.repeat(limit)}));
    const before=await snapshot(f.folder); const child=run(f);
    assert.equal(child.status,1); assert.match(child.stderr,/size limit/); assert.equal(child.stdout,'');
    assert.deepEqual(await snapshot(f.folder),before);
  });
}

test('parser and context failures never expose private bodies or stack traces',async t=>{
  const f=await fixture(t);
  for(const bytes of ['{"private-marker-secret": broken}',JSON.stringify({...vector.request,context:{...vector.request.context,maximumRisk:'private-marker-secret'}}),Buffer.from([0xff,0xfe])]) {
    await writeFile(f.request,bytes); const before=await snapshot(f.folder); const child=run(f);
    assert.equal(child.status,1); assert.doesNotMatch(child.stderr,/private-marker-secret|\n\s+at /);
    assert.equal(child.stdout,''); assert.deepEqual(await snapshot(f.folder),before);
  }
});

test('result path must refer to a regular file',async t=>{
  const f=await fixture(t); const child=run(f,[...f.args.slice(0,5),f.folder]);
  assert.equal(child.status,1); assert.equal(child.stdout,'');
});
