import {pathToFileURL} from 'node:url';
import {resolve} from 'node:path';
import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
const file=resolve(process.argv[2]),{consume}=await import(pathToFileURL(file));
const context={requestId:'q7',revision:'rev3',allowedIds:['a','b']};
const valid={version:1,requestId:'q7',revision:'rev3',outcome:'complete',records:[{id:'a',enabled:false,score:0},{id:'b',enabled:true,score:null}]};
const e=p=>({transport:'complete',payload:JSON.stringify(p)}),cases=[];
const add=(name,event,status,extra=()=>{})=>cases.push({name,event,status,extra});
add('false zero null preserved',e(valid),'accepted',r=>assert.deepEqual(r.records,valid.records));
add('empty records valid',e({...valid,records:[]}),'accepted',r=>assert.deepEqual(r.records,[]));
add('maximum score valid',e({...valid,records:[{id:'a',enabled:true,score:1}]}),'accepted');
add('abstention is unavailable',e({version:1,requestId:'q7',revision:'rev3',outcome:'abstained',reason:'Evidence missing'}),'unavailable');
for(const transport of ['refused','unavailable','cancelled'])add(transport,{transport,payload:e(valid).payload},'unavailable');
add('parseable streaming not complete',{transport:'streaming',payload:e(valid).payload},'pending');
add('unknown transport',{transport:'success',payload:e(valid).payload},'invalid');
add('missing event',null,'invalid');
add('payload must be text',{transport:'complete',payload:valid},'invalid');
add('malformed JSON',{transport:'complete',payload:'{"x":'},'invalid');
add('trailing prose',{transport:'complete',payload:e(valid).payload+' thanks'},'invalid');
add('UTF8 byte limit',e({version:1,requestId:'q7',revision:'rev3',outcome:'abstained',reason:'🔥'.repeat(1100)}),'invalid');
const abstain={version:1,requestId:'q7',revision:'rev3',outcome:'abstained',reason:''};
add('exact byte limit valid',e({...abstain,reason:'x'.repeat(4096-Buffer.byteLength(JSON.stringify(abstain)))}),'unavailable');
add('safe parse failure reason',{transport:'complete',payload:'private_token_8e93 invalid JSON'},'invalid',r=>assert.ok(!r.reason.includes('private_token_8e93')));
for(const [name,patch] of [['wrong request',{requestId:'q6'}],['stale revision',{revision:'rev2'}],['wrong version',{version:2}],['coerced version',{version:'1'}],['unknown field',{permission:'approved'}],['unknown outcome',{outcome:'maybe'}]])add(name,e({...valid,...patch}),'invalid');
for(const [name,records] of [['unknown id',[{id:'z',enabled:true,score:0.5}]],['duplicate id',[valid.records[0],valid.records[0]]],['number id',[{id:1,enabled:true,score:0.5}]],['boolean coercion',[{id:'a',enabled:'false',score:0.5}]],['numeric coercion',[{id:'a',enabled:true,score:'0.5'}]],['missing score',[{id:'a',enabled:true}]],['negative score',[{id:'a',enabled:true,score:-0.1}]],['score above one',[{id:'a',enabled:true,score:1.1}]],['extra record field',[{id:'a',enabled:true,score:1,execute:true}]],['null record',[null]],['object not array',{}]])add(name,e({...valid,records}),'invalid');
add('array payload',e([]),'invalid');add('null payload',e(null),'invalid');
add('blank abstention',e({version:1,requestId:'q7',revision:'rev3',outcome:'abstained',reason:'  '}),'invalid');
add('abstention cannot carry records',e({...valid,outcome:'abstained',reason:'No answer'}),'invalid');
add('overflow numeric literal',{transport:'complete',payload:'{"version":1,"requestId":"q7","revision":"rev3","outcome":"complete","records":[{"id":"a","enabled":true,"score":1e400}]}'},'invalid');
const results=[];
for(const c of cases){try{const event=structuredClone(c.event),ctx=structuredClone(context);const r=consume(event,ctx);assert.equal(r?.status,c.status);assert.deepEqual(event,c.event);assert.deepEqual(ctx,context);if(['invalid','unavailable'].includes(c.status))assert.ok(typeof r.reason==='string'&&r.reason.trim());c.extra(r);results.push({name:c.name,passed:true});}catch(error){results.push({name:c.name,passed:false,error:error.message});}}
const report={schema:'godskills-instruction-exercise-v1',design:'single-assisted-contract-exercise-no-baseline',implementationSha256:createHash('sha256').update(await readFile(file)).digest('hex'),cases:results.length,passed:results.filter(x=>x.passed).length,results};
if(process.argv[3])await writeFile(resolve(process.argv[3]),JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify(report));if(report.passed!==report.cases)process.exitCode=1;
